gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
  
rvm:
  - 2.2.0
  - 2.1.5
  - 2.0.0
  - 1.9.3
